[build]
  command = "bunx xyd-js build"
  publish = ".xyd/build/client"
  
[[redirects]]
  from = "/"
  to = "/docs/overview"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/docs/overview"
  status = 301
  force = true
